# Generated by Django 4.2 on 2025-05-28 12:46

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
            ],
            options={"db_table": "cart",},
        ),
        migrations.CreateModel(
            name="Cartresult_Sparkstream",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("times", models.IntegerField()),
            ],
            options={"db_table": "cartresult_sparkstream",},
        ),
        migrations.CreateModel(
            name="Clickresult_Sparkstream",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("times", models.IntegerField()),
            ],
            options={"db_table": "clickresult_sparkstream",},
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
            ],
            options={"db_table": "collection",},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
            ],
            options={"db_table": "comment",},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(default=datetime.datetime.utcnow)),
                ("headline", models.CharField(max_length=100)),
                ("excerpt", models.CharField(max_length=100)),
                ("content", models.TextField()),
            ],
            options={"db_table": "news",},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("total_price", models.FloatField()),
                ("user_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
            ],
            options={"db_table": "order",},
        ),
        migrations.CreateModel(
            name="Orderesult_Sparkstream",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("times", models.IntegerField()),
                ("date", models.CharField(max_length=100)),
            ],
            options={"db_table": "orderesult_sparkstream",},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("image", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("user_id", models.IntegerField()),
            ],
            options={"db_table": "product",},
        ),
        migrations.CreateModel(
            name="SearchResult_Sparkstream",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("times", models.IntegerField()),
            ],
            options={"db_table": "searchresult_sparkstream",},
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=datetime.datetime.utcnow
                    ),
                ),
            ],
            options={"db_table": "track",},
        ),
        migrations.CreateModel(
            name="TrackCart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("product_id", models.IntegerField()),
                ("user_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "track_cart",},
        ),
        migrations.CreateModel(
            name="TrackClick",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.IntegerField()),
                ("event_type", models.CharField(max_length=50)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "track_click",},
        ),
        migrations.CreateModel(
            name="TrackOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("product_id", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "track_order",},
        ),
        migrations.CreateModel(
            name="TrackSearch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "track_search",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=120, unique=True),
                ),
                (
                    "registered_on",
                    models.DateTimeField(default=datetime.datetime.utcnow),
                ),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="backend_store_user_groups",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="backend_store_user_permissions",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"db_table": "user",},
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
