# """
# Django settings for Django_MainProject project.

# Generated by 'django-admin startproject' using Django 4.2.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-jpqi(xbiv@shy)(*@9_juwf9t(fhldepga6d_j$kwf(p!dn)-o"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'Backend_Store',
#     'corsheaders',
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware', 
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# #允许跨域
# #ORS_ORIGIN_ALLOW_ALL = True
# ROOT_URLCONF = "Django_MainProject.urls"
# SESSION_COOKIE_SAMESITE = 'None'  # 或 'None'（需配合HTTPS）
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_NAME = 'sessionid'  # 保持默认
# SESSION_COOKIE_AGE = 86400  # 1天过期
# CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript读取
# CSRF_COOKIE_SECURE = False
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:8080',
#     'http://127.0.0.1:8000'
# ]

# # 允许携带Cookie
# CORS_ALLOW_CREDENTIALS = True

# # 允许的HTTP方法
# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# # 允许的请求头
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     'x-sessionid',  # 自定义Session头
# ]

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": ['frontend/dist'],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "Django_MainProject.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'django_database',
#         'USER': 'root',
#         'PASSWORD': '123456',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#             'init_command': 'SET default_storage_engine=INNODB',
#         },
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "static/"
# STATICFILES_DIRS = [
#     Path(BASE_DIR) / "frontend/dist/static",
# ]

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# # 指定自定义用户模型
# # AUTH_USER_MODEL = 'Backend_Store.User'

"""
Django settings for Django_MainProject project.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-jpqi(xbiv@shy)(*@9_juwf9t(fhldepga6d_j$kwf(p!dn)-o"
DEBUG = True
ALLOWED_HOSTS = ['*']  # 开发环境允许所有主机

# ================== 应用和中间件配置 ==================
INSTALLED_APPS = [
    'corsheaders',  # 必须放在前面
    'Backend_Store',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 必须第一个
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ================== 跨域配置 ==================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8080",
]
SESSION_COOKIE_DOMAIN = 'None'  
CSRF_COOKIE_DOMAIN = 'localhost'
CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']  # 暴露自定义头

# ================== 会话和Cookie配置 ==================
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 86400  # 24小时
SESSION_COOKIE_SAMESITE = 'None'  # 跨站传递Cookie
SESSION_COOKIE_SECURE = False  # 开发环境可False
SESSION_COOKIE_HTTPONLY = True  # 防止XSS

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False  # 允许JS读取
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS  # 同步跨域配置

# ================== 其他配置 ==================
ROOT_URLCONF = "Django_MainProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'frontend/dist')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Django_MainProject.wsgi.application"

# ================== 数据库配置 ==================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_database',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': 'SET default_storage_engine=INNODB',
        },
    }
}

# ================== 密码验证 ==================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
]

# ================== 国际化 ==================
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# ================== 静态文件 ==================
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/dist/static"),
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ================== 生产环境检查 ==================
if not DEBUG:
    # 生产环境必须启用HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 限制允许的主机
    ALLOWED_HOSTS = ['your-production-domain.com']